title: "My Blog"

# 배너에 쓸 값
name: "Hyemin Song"
user_title: "Backend Developer"
user_description: "Java/JS/SQL 좋아하는 개발자"

email: "hyeminsSsong@example.com"

url: "https://hyeminSsong.github.io"
baseurl: "/git_test"

remote_theme: sujaykundu777/devlopr-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# (선택) 테마가 author.*를 참조할 수도 있어 대비
# author:
#  name: "Hyemin Song"

# (선택) 프로필 이미지 경로
# avatar: "/assets/img/profile.jpg"